# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://fengqiuadamdong.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Dr Fengqiu Adam Dong
# Description of the Site
description: Jansky Fellow at NRAO
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/Full_chime_night_3.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: adong@nrao.edu

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: FAD

# Name of the Author
author-name: Fengqiu Adam Dong
# URL for the Image of the Author
about-image: /assets/images/casca2024_zoom.png

author-image: /assets/images/Headshot.png
  # 60 Words About the Author
author-about: I am an astrophysicist who works on the Canadian Hydrogen Intensity Mapping Experiment. My research spans many fields across compact objects. I study an array of compact objects such as Long Period Transients, Pulsars, and Fast Radio Bursts. I lead the largest single pulse pulsar survey to date. Furthermore, I lead the pulsar working group with the CHIME VLBI outriggers. CHIME/LPT working group...
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://orcid.org/0000-0003-4098-5222

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
#permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
